//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaintainenceApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class guest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public guest()
        {
            this.booking = new HashSet<booking>();
        }
    
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string phoneNr { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string username { get; set; }
        public string pass { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<booking> booking { get; set; }
    }
}
