//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaintainenceApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Hotel_ManagerEntities : DbContext
    {
        public Hotel_ManagerEntities()
            : base("name=Hotel_ManagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<booking> booking { get; set; }
        public virtual DbSet<cleanRequest> cleanRequest { get; set; }
        public virtual DbSet<guest> guest { get; set; }
        public virtual DbSet<maintainenceRequest> maintainenceRequest { get; set; }
        public virtual DbSet<room> room { get; set; }
        public virtual DbSet<roomService> roomService { get; set; }
    }
}
