//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class guest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public guest()
        {
            this.bookings = new HashSet<booking>();
        }

        [Key]
        public int UserID { get; set; }

        [Required(ErrorMessage = "First name is required.")]
        public string firstname { get; set; }

        [Required(ErrorMessage = "Last name is required.")]
        public string lastname { get; set; }

        [Required(ErrorMessage = "Phone number is required.")]
        public string phoneNr { get; set; }

        [Required(ErrorMessage = "Birth date is required.")]
        public Nullable<System.DateTime> dob { get; set; }

        [Required(ErrorMessage = "Username is required.")]
        public string username { get; set; }

        [Required(ErrorMessage = "Password is required.")]
        [DataType(DataType.Password)]
        public string pass { get; set; }

        [Compare("pass", ErrorMessage ="Please comfirm your password.")]
        [DataType(DataType.Password)]
        public string confirmPass { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<booking> bookings { get; set; }
    }
}
